dyn_obj:
    points_topic: "/cloud_registered_body"  # 등록된 포인트 클라우드의 토픽
    odom_topic: "/aft_mapped_to_init"  # 로봇의 위치 및 자세 정보가 담긴 토픽
    frame_id: "camera_init"  # 카메라 초기화 프레임의 ID
    pc_topic: "/lidar_top"  # LIDAR 포인트 클라우드의 토픽

    dataset: 1 # 데이터셋 종류 (0: KITTI, 1: NuScenes, 2: Waymo, 3: Avia)
    buffer_delay: 0.1  # 버퍼 지연 시간
    buffer_size: 500000  # 버퍼 크기
    points_num_perframe: 50000  # 각 프레임에서의 포인트 수
    depth_map_dur: 0.2  # 깊이 맵의 지속 시간
    max_depth_map_num: 10  # 최대 깊이 맵 수
    max_pixel_points: 50  # 최대 픽셀 포인트 수
    frame_dur: 0.05  # 프레임 간 지속 시간
    self_x_f: 2.5  # 로봇의 x축 전방 제한
    self_x_b: -1.5  # 로봇의 x축 후방 제한
    self_y_l: 0  # 로봇의 y축 좌측 제한
    self_y_r: -0  # 로봇의 y축 우측 제한
    blind_dis: 0.2  # 맹점 거리
    fov_up: 10.0  # 시야 상단 각도
    fov_down: -30.0  # 시야 하단 각도
    fov_left: 180.0  # 시야 왼쪽 각도
    fov_right: -180.0  # 시야 오른쪽 각도
    fov_cut: 0  # 시야 잘라내기 각도
    checkneighbor_range: 1  # 이웃 범위 확인

    depth_thr1: 0.15  # 첫 번째 깊이 임계값
    enter_min_thr1: 1.0  # 첫 번째 진입 최소 임계값 (벽 근처의 자동차 포인트 제거, 뷰 변경 관련)
    enter_max_thr1: 0.3  # 첫 번째 진입 최대 임계값 (벽 근처에 있는 보행자를 안전하게 유지)
    map_cons_depth_thr1: 0.3  # 맵에서의 깊이 조건1
    map_cons_hor_thr1: 0.01  # 맵에서의 수평 조건1
    map_cons_ver_thr1: 0.03  # 맵에서의 수직 조건1
    map_cons_hor_dis1: 0.15  # 맵에서의 수평 거리 조건1
    map_cons_ver_dis1: 0.15  # 맵에서의 수직 거리 조건1
    depth_cons_depth_thr1: 0.5  # 깊이 조건 깊이 임계값1
    depth_cons_depth_max_thr1: 1.0  # 최대 깊이 조건1
    depth_cons_hor_thr1: 0.02  # 깊이 조건 수평 임계값1
    depth_cons_ver_thr1: 0.01  # 깊이 조건 수직 임계값1
    enlarge_z_thr1: -2.5  # 깊이 확대 임계값1
    enlarge_angle: 2.0  # 각도 확대 값
    enlarge_depth: 3.0  # 깊이 확대 값
    occluded_map_thr1: 2  # 가려진 맵 임계값1
    case1_interp_en: true  # 첫 번째 케이스의 보간 활성화 여부

    v_min_thr2: 1.0  # 두 번째 최소 속도 임계값
    acc_thr2: 7.0  # 두 번째 가속도 임계값
    map_cons_depth_thr2: 0.2  # 두 번째 맵에서의 깊이 조건
    map_cons_hor_thr2: 0.01  # 두 번째 맵에서의 수평 조건
    map_cons_ver_thr2: 0.03  # 두 번째 맵에서의 수직 조건
    occ_depth_thr2: 10.15  # 두 번째 가려진 깊이 임계값
    occ_hor_thr2: 0.01  # 두 번째 가려진 수평 임계값
    occ_ver_thr2: 0.04  # 두 번째 가려진 수직 임계값
    depth_cons_depth_thr2: 0.1  # 두 번째 깊이 조건
    depth_cons_depth_max_thr2: 0.5  # 두 번째 최대 깊이 조건
    depth_cons_hor_thr2: 0.01  # 두 번째 깊이 조건 수평 임계값
    depth_cons_ver_thr2: 0.03  # 두 번째 깊이 조건 수직 임계값
    occluded_times_thr2: 2  # 두 번째 가려진 횟수 임계값
    k_depth2: 0.005  # 두 번째 깊이 상수
    case2_interp_en: false  # 두 번째 케이스의 보간 활성화 여부

    v_min_thr3: 0.5  # 세 번째 최소 속도 임계값
    acc_thr3: 15.0  # 세 번째 가속도 임계값
    map_cons_depth_thr3: 0.2  # 세 번째 맵에서의 깊이 조건
    map_cons_hor_thr3: 0.01  # 세 번째 맵에서의 수평 조건
    map_cons_ver_thr3: 0.03  # 세 번째 맵에서의 수직 조건
    occ_depth_thr3: 0.15  # 세 번째 가려진 깊이 임계값
    occ_hor_thr3: 0.01  # 세 번째 가려진 수평 임계값
    occ_ver_thr3: 0.04  # 세 번째 가려진 수직 임계값
    depth_cons_depth_thr3: 0.3  # 세 번째 깊이 조건
    depth_cons_depth_max_thr3: 1.0  # 세 번째 최대 깊이 조건
    depth_cons_hor_thr3: 0.01  # 세 번째 깊이 조건 수평 임계값
    depth_cons_ver_thr3: 0.03  # 세 번째 깊이 조건 수직 임계값
    occluding_times_thr3: 2  # 세 번째 가려진 횟수 임계값
    case3_interp_en: false  # 세 번째 케이스의 보간 활성화 여부

    interp_hor_thr: 0.015  # 수평 보간 임계값
    interp_ver_thr: 0.06  # 수직 보간 임계값
    interp_thr1: 1.5  # 첫 번째 보간 임계값
    interp_static_max: 10.0  # 정적 물체에 대한 최대 보간값
    interp_start_depth1: 15  # 첫 번째 보간 시작 깊이
    interp_kp1: 0.15  # 첫 번째 비례 게인
    interp_kd1: 1.5  # 첫 번째 미분 게인
    interp_bg: 0.8  # 배경 보간 값
    interp_thr2: 0.25  # 두 번째 보간 임계값
    interp_thr3: 0.05  # 세 번째 보간 임계값

    point_index: -1  # 포인트 인덱스 초기값
    debug_x: 7.2065  # 디버깅 x 좌표
    debug_y: -3.1844  # 디버깅 y 좌표
    debug_z: -0.89005  # 디버깅 z 좌표

    cluster_coupled: true  # 클러스터 결합 여부
    cluster_future: true  # 미래 클러스터 여부
    cluster_extend_pixel: 3  # 클러스터 확장 픽셀 수
    cluster_min_pixel_number: 3  # 최소 클러스터 픽셀 수
    cluster_Voxel_revolusion: 0.3  # 클러스터 Voxel 변환 비율

    dyn_filter_en: false  # 동적 필터 활성화 여부
    debug_publish: false  # 디버깅 출판 여부

    ver_resolution_max: 0.022  # 수직 해상도 최대값
    hor_resolution_max: 0.007  # 수평 해상도 최대값
