dyn_obj:
    points_topic: "/cloud_registered_body"  # 포인트 클라우드가 저장된 토픽
    odom_topic: "/aft_mapped_to_init"  # 로봇의 위치 추적 정보가 저장된 토픽
    frame_id: "camera_init"  # 카메라 프레임의 ID
    pc_topic: "/livox/lidar"  # LIDAR 포인트 클라우드 토픽

    dataset: 3 #0: KITTI, 1: NuScenes, 2: Waymo, 3: Avia 데이터셋 선택
    buffer_delay: 0.1  # 버퍼 지연 시간
    buffer_size: 300000  # 버퍼 크기
    points_num_perframe: 100000  # 각 프레임 당 포인트의 수
    depth_map_dur: 0.2  # 깊이 맵의 지속 시간
    max_depth_map_num: 5  # 최대 깊이 맵 수
    max_pixel_points: 50  # 최대 픽셀 포인트 수
    frame_dur: 0.1  # 프레임 간 지속 시간
    self_x_f: -2.5  # 로봇의 x축 전방 한계
    self_x_b: -1.5  # 로봇의 x축 후방 한계
    self_y_l: -1.6  # 로봇의 y축 좌측 한계
    self_y_r: -1.6  # 로봇의 y축 우측 한계
    blind_dis: 0.5  # 맹점 거리
    fov_up: 38.6  # 시야의 상단 각도
    fov_down: -38.6  # 시야의 하단 각도
    fov_left: 34.0  # 시야의 좌측 각도
    fov_right: -34.0  # 시야의 우측 각도
    fov_cut: -20.0  # 시야 잘라내기 각도
    
    depth_thr1: 0.15  # 깊이 임계값1
    enter_min_thr1: 1.0  # 진입 최소 임계값1
    enter_max_thr1: 0.3  # 진입 최대 임계값1
    map_cons_depth_thr1: 0.3  # 맵에서의 깊이 조건1
    map_cons_hor_thr1: 0.01  # 맵에서의 수평 조건1
    map_cons_ver_thr1: 0.02  # 맵에서의 수직 조건1
    map_cons_hor_dis1: 0.1  # 맵에서의 수평 거리 조건1
    map_cons_ver_dis1: 0.1  # 맵에서의 수직 거리 조건1
    depth_cons_depth_thr1: 0.5  # 깊이 조건 깊이 임계값1
    depth_cons_depth_max_thr1: 1.0  # 최대 깊이 조건1
    depth_cons_hor_thr1: 0.01  # 깊이 조건 수평 임계값1
    depth_cons_ver_thr1: 0.01  # 깊이 조건 수직 임계값1
    enlarge_z_thr1: -2.5  # z축 확대 임계값1
    enlarge_angle: 2.0  # 각도 확대 값
    enlarge_depth: 3.0  # 깊이 확대 값
    occluded_map_thr1: 2  # 가려진 맵 임계값1
    case1_interp_en: false  # 첫 번째 케이스의 보간법 활성화 여부

    v_min_thr2: 0.5  # 최소 속도 임계값2
    acc_thr2: 7.0  # 가속도 임계값2
    map_cons_depth_thr2: 0.1  # 맵에서의 깊이 조건2
    map_cons_hor_thr2: 0.01  # 맵에서의 수평 조건2
    map_cons_ver_thr2: 0.01  # 맵에서의 수직 조건2
    occ_depth_thr2: 0.15  # 가려진 깊이 임계값2
    occ_hor_thr2: 0.02  # 가려진 수평 임계값2
    occ_ver_thr2: 0.03  # 가려진 수직 임계값2
    depth_cons_depth_thr2: 0.1  # 깊이 조건 깊이 임계값2
    depth_cons_depth_max_thr2: 0.5  # 최대 깊이 조건2
    depth_cons_hor_thr2: 0.01  # 깊이 조건 수평 임계값2
    depth_cons_ver_thr2: 0.01  # 깊이 조건 수직 임계값2
    occluded_times_thr2: 2  # 가려진 횟수 임계값2
    k_depth2: 0.005  # 깊이 조건 상수2
    case2_interp_en: false  # 두 번째 케이스의 보간법 활성화 여부

    v_min_thr3: 0.5  # 최소 속도 임계값3
    acc_thr3: 15.0  # 가속도 임계값3
    map_cons_depth_thr3: 0.2  # 맵에서의 깊이 조건3
    map_cons_hor_thr3: 0.015  # 맵에서의 수평 조건3
    map_cons_ver_thr3: 0.015  # 맵에서의 수직 조건3
    occ_depth_thr3: 0.15  # 가려진 깊이 임계값3
    occ_hor_thr3: 0.01  # 가려진 수평 임계값3
    occ_ver_thr3: 0.01  # 가려진 수직 임계값3
    depth_cons_depth_thr3: 0.3  # 깊이 조건 깊이 임계값3
    depth_cons_depth_max_thr3: 1.0  # 최대 깊이 조건3
    depth_cons_hor_thr3: 0.01  # 깊이 조건 수평 임계값3
    depth_cons_ver_thr3: 0.01  # 깊이 조건 수직 임계값3
    occluding_times_thr3: 2  # 가려진 횟수 임계값3
    case3_interp_en: false  # 세 번째 케이스의 보간법 활성화 여부

    interp_hor_thr: 0.015  # 수평 보간 임계값
    interp_ver_thr: 0.015  # 수직 보간 임계값
    interp_thr1: 0.5  # 첫 번째 보간 임계값
    interp_static_max: 10.0  # 정적 물체 최대 보간값
    interp_start_depth1: 10  # 보간 시작 깊이1
    interp_kp1: 0.1  # 비례 게인1
    interp_kd1: 0.5  # 미분 게인1
    interp_bg: 0.8  # 배경 보간 값
    interp_thr2: 0.25  # 두 번째 보간 임계값
    interp_thr3: 0.05  # 세 번째 보간 임계값

    point_index: -1  # 포인트 인덱스 초기값
    debug_x: 7.2065  # 디버깅 x좌표
    debug_y: -3.1844  # 디버깅 y좌표
    debug_z: -0.89005  # 디버깅 z좌표
    cluster_coupled: true  # 클러스터 결합 활성화 여부
    cluster_future: true  # 미래 클러스터 활성화 여부
    cluster_extend_pixel: 2  # 클러스터 확장 픽셀 수
    cluster_min_pixel_number: 3  # 최소 클러스터 픽셀 수
    cluster_thrustable_thresold: 0.3  # 클러스터 신뢰 임계값
    cluster_Voxel_revolusion: 0.3  # 클러스터 Voxel 변환 비율

    dyn_filter_en: false  # 동적 필터 활성화 여부
    debug_publish: false  # 디버깅 출판 여부
    

    ver_resolution_max: 0.005  # 수직 해상도의 최대값
    hor_resolution_max: 0.005  # 수평 해상도의 최대값
